# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VikasitCode < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/Vikasit-AI/vikasit-code"
  version "2.2.10"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Vikasit-AI/releases/releases/download/v2.2.10/vikasit-code-darwin-x64.zip"
      sha256 "f5902a71315160e726e6784df2423f0756f2070bb7184c6578926b9250e5371d"

      def install
        bin.install "vikasit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Vikasit-AI/releases/releases/download/v2.2.10/vikasit-code-darwin-arm64.zip"
      sha256 "491d0a38e9cc7e38e5ee5ed7c7d64e896589039e28bdb0b0da10a403af5853dc"

      def install
        bin.install "vikasit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Vikasit-AI/releases/releases/download/v2.2.10/vikasit-code-linux-x64.tar.gz"
      sha256 "5f10491bc1e403bc9df218c539fd258572e6155ea537228ba0d8ec83264a6334"
      def install
        bin.install "vikasit"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Vikasit-AI/releases/releases/download/v2.2.10/vikasit-code-linux-arm64.tar.gz"
      sha256 "026a148f0e013b15606b8897aefffb6821c25d2166cfe9b4dd3d37d18db62180"
      def install
        bin.install "vikasit"
      end
    end
  end
end

