# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VikasitCode < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/Vikasit-AI/vikasit-code"
  version "2.1.0"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Vikasit-AI/releases/releases/download/v2.1.0/vikasit-code-darwin-x64.zip"
      sha256 "58d3f4ab787b3c524445d61394bf70f9aeef2cc1e7007eaf6cb8c20b66e182ef"

      def install
        bin.install "vikasit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Vikasit-AI/releases/releases/download/v2.1.0/vikasit-code-darwin-arm64.zip"
      sha256 "6a95d252c770181e743bd9a10da714ae81361250a08c5659ae95d12d5a76d9ec"

      def install
        bin.install "vikasit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Vikasit-AI/releases/releases/download/v2.1.0/vikasit-code-linux-x64.tar.gz"
      sha256 "dd8d4963a54196ea33905de2d5d6a358417bfb9059d2e800007912da76620c94"
      def install
        bin.install "vikasit"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Vikasit-AI/releases/releases/download/v2.1.0/vikasit-code-linux-arm64.tar.gz"
      sha256 "9db1a2d17decadfef0cd920ebb7cb456019419f9f7e66831f915ac6c6e340c2a"
      def install
        bin.install "vikasit"
      end
    end
  end
end

